# Generated by Django 4.0.5 on 2022-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('service1', models.CharField(max_length=55)),
                ('service2', models.CharField(max_length=55)),
                ('service3', models.CharField(max_length=55)),
                ('service4', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services_images')),
                ('title', models.CharField(max_length=155)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services_introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('text', models.TextField()),
                ('cause1', models.CharField(max_length=255)),
                ('cause2', models.CharField(max_length=255)),
                ('cause3', models.CharField(max_length=255)),
                ('cause4', models.CharField(max_length=255)),
                ('cause5', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services_images')),
            ],
        ),
        migrations.CreateModel(
            name='Services_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
