# Generated by Django 4.0.5 on 2022-06-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_introduction',
            name='cause5',
        ),
    ]
