# Generated by Django 4.0.5 on 2022-06-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='about_images')),
                ('image2', models.ImageField(upload_to='about_images')),
                ('image3', models.ImageField(upload_to='about_images')),
                ('image4', models.ImageField(upload_to='about_images')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('topic_title1', models.CharField(max_length=150)),
                ('topic_text1', models.TextField()),
                ('topic_title2', models.CharField(max_length=150)),
                ('topic_text2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='banner_image')),
                ('background_image', models.ImageField(upload_to='banner_background_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bot_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Center_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('price', models.FloatField()),
                ('offer1', models.CharField(max_length=155)),
                ('offer2', models.CharField(max_length=155)),
                ('offer3', models.CharField(max_length=155)),
                ('offer4', models.CharField(max_length=155)),
                ('offer5', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feauters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('feature1', models.CharField(max_length=50)),
                ('feature2', models.CharField(max_length=50)),
                ('feature3', models.CharField(max_length=50)),
                ('feature4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intro_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('background_image', models.ImageField(upload_to='video_background_image')),
                ('video_url', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Left_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('price', models.FloatField()),
                ('offer1', models.CharField(max_length=155)),
                ('offer2', models.CharField(max_length=155)),
                ('offer3', models.CharField(max_length=155)),
                ('offer4', models.CharField(max_length=155)),
                ('offer5', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Packages_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Right_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('price', models.FloatField()),
                ('offer1', models.CharField(max_length=155)),
                ('offer2', models.CharField(max_length=155)),
                ('offer3', models.CharField(max_length=155)),
                ('offer4', models.CharField(max_length=155)),
                ('offer5', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services_images')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Site_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Testimionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimionals_images')),
            ],
        ),
        migrations.CreateModel(
            name='Testimionals_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image1', models.ImageField(upload_to='testimionals_text_images')),
                ('image2', models.ImageField(upload_to='testimionals_text_images')),
                ('image3', models.ImageField(upload_to='testimionals_text_images')),
                ('image4', models.ImageField(upload_to='testimionals_text_images')),
                ('image5', models.ImageField(upload_to='testimionals_text_images')),
                ('image6', models.ImageField(upload_to='testimionals_text_images')),
            ],
        ),
    ]
