# Generated by Django 4.0.5 on 2022-06-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center_package',
            name='timeframe',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='left_package',
            name='timeframe',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='right_package',
            name='timeframe',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
