# Generated by Django 4.0.5 on 2022-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_number_form_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_form_text',
            name='background_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
