# Generated by Django 4.0.5 on 2022-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_number_form_text_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
            ],
        ),
    ]
