# Generated by Django 4.0.5 on 2022-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('title1', models.CharField(max_length=255)),
                ('text1', models.TextField()),
                ('title2', models.CharField(max_length=255)),
                ('text2', models.TextField()),
                ('image1', models.ImageField(upload_to='about_images')),
                ('image2', models.ImageField(upload_to='about_images')),
                ('image3', models.ImageField(upload_to='about_images')),
                ('image4', models.ImageField(upload_to='about_images')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_images')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
